# Docker setup para evitar problemas do Windows
version: '3.8'
services:
  app:
    image: php:8.2-cli
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y git unzip libzip-dev &&
        docker-php-ext-install pdo_mysql zip &&
        curl -sS https://getcomposer.org/installer | php &&
        mv composer.phar /usr/local/bin/composer &&
        composer install --no-dev --optimize-autoloader &&
        php artisan key:generate &&
        php artisan migrate --seed &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=portal_corporativo
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portal_corporativo
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysql_data:
